[package]
name = "gonnawintheleague"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
relative-path = "1.9.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["std"] }
