[package]
name = "gonnawintheleague"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
rand = "0.9.0"
reqwest = { version = "0.12.14", features = ["blocking", "json"] }
scraper = "0.23.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
